version: '3'
services: 
    nlp-api-image:
        build: .
        container_name: "nlp-api-container"
        ports: 
            - "80:8080"
        volumes:
            - ./alphago:/alphago
        restart: unless-stopped